SFTP_USERS_GID=${SFTP_USERS_GID:-'2000'}

declare -A SSHD_CONFIG
SSHD_CONFIG["LISTEN_PORT"]=${LISTEN_PORT:-'222'}
SSHD_CONFIG["LISTEN_ADDRESS"]=${LISTEN_ADDRESS:-'0.0.0.0'}
SSHD_CONFIG["MAX_AUTH_TRIES"]=${MAX_AUTH_TRIES:-'3'}
SSHD_CONFIG["MAX_SESSIONS"]=${MAX_SESSIONS:-'3'}